### ISSUE TITLE
Attempt to unlock a mutex which is locked by another thread

### ISSUE THREAD

**Issue by sfcgeorge** [machinio/cuprite#76]
Switched a test suite with a few hundred specs to Cuprite, mostly working fine (well done and thank you!)

There's 1 weird error we get. The spec passes normally, but if we turn on `js_errors: true` we get this:

```
Failures:

  1) Enthusiast an enthusiast successfully books an activity that disallows kids
     Failure/Error: dashboard_page.browse_activities.click
     
     ThreadError:
       Attempt to unlock a mutex which is locked by another thread
     # ./spec/features/enthusiasts/books_an_activity_spec.rb:151:in `navigate_to_booking_page'
     # ./spec/features/enthusiasts/books_an_activity_spec.rb:36:in `block (2 levels) in <main>'
     # -e:1:in `<main>'
     # ------------------
     # --- Caused by: ---
     # Capybara::Cuprite::JavaScriptError:
     #   r
     #   ./spec/features/enthusiasts/books_an_activity_spec.rb:151:in `navigate_to_booking_page'
```

Mutex seems like a Ruby thing not a JS thing, yet a JS error is being raised. And the JS error is just the letter "r"?

The scenario is just logging in, being redirected to the dashboard, then clicking a link. On clicking the link this error happens.

For now I've worked around like so:

```
begin
  click_on 'Search'
  # visit '/search' # same error
rescue ThreadError
  puts 'Rescuing erroneous Cuprite JS error on search page'
end
```
